package docs

// Переименования Godot 3 -> Godot 4, которые модели чаще всего путают.
// Ключи в нижнем регистре. Полный список — в конвертере проекта движка
// (godot --convert-3to4), но он не доступен как данные, а здесь нужны
// самые частые случаи с пояснением.

// classRenames: старый класс -> новый (или "" если класс убран) и пояснение.
var classRenames = map[string]struct{ New, Note string }{
	"kinematicbody2d":               {"CharacterBody2D", ""},
	"kinematicbody":                 {"CharacterBody3D", ""},
	"kinematiccollision":            {"KinematicCollision3D", ""},
	"spatial":                       {"Node3D", ""},
	"sprite":                        {"Sprite2D", ""},
	"animatedsprite":                {"AnimatedSprite2D", ""},
	"position2d":                    {"Marker2D", ""},
	"position3d":                    {"Marker3D", ""},
	"particles2d":                   {"GPUParticles2D", ""},
	"particles":                     {"GPUParticles3D", ""},
	"cpuparticles":                  {"CPUParticles3D", ""},
	"visibilitynotifier2d":          {"VisibleOnScreenNotifier2D", ""},
	"visibilitynotifier":            {"VisibleOnScreenNotifier3D", ""},
	"visibilityenabler2d":           {"VisibleOnScreenEnabler2D", ""},
	"visibilityenabler":             {"VisibleOnScreenEnabler3D", ""},
	"raycast":                       {"RayCast3D", ""},
	"area":                          {"Area3D", ""},
	"rigidbody":                     {"RigidBody3D", ""},
	"staticbody":                    {"StaticBody3D", ""},
	"physicsbody":                   {"PhysicsBody3D", ""},
	"collisionobject":               {"CollisionObject3D", ""},
	"collisionshape":                {"CollisionShape3D", ""},
	"collisionpolygon":              {"CollisionPolygon3D", ""},
	"camera":                        {"Camera3D", ""},
	"meshinstance":                  {"MeshInstance3D", ""},
	"multimeshinstance":             {"MultiMeshInstance3D", ""},
	"directionallight":              {"DirectionalLight3D", ""},
	"omnilight":                     {"OmniLight3D", ""},
	"spotlight":                     {"SpotLight3D", ""},
	"light":                         {"Light3D", ""},
	"path":                          {"Path3D", ""},
	"pathfollow":                    {"PathFollow3D", ""},
	"skeleton":                      {"Skeleton3D", ""},
	"boneattachment":                {"BoneAttachment3D", ""},
	"springarm":                     {"SpringArm3D", ""},
	"softbody":                      {"SoftBody3D", ""},
	"vehiclebody":                   {"VehicleBody3D", ""},
	"vehiclewheel":                  {"VehicleWheel3D", ""},
	"remotetransform":               {"RemoteTransform3D", ""},
	"visualinstance":                {"VisualInstance3D", ""},
	"geometryinstance":              {"GeometryInstance3D", ""},
	"listener":                      {"AudioListener3D", ""},
	"listener2d":                    {"AudioListener2D", ""},
	"csgbox":                        {"CSGBox3D", ""},
	"csgsphere":                     {"CSGSphere3D", ""},
	"csgcylinder":                   {"CSGCylinder3D", ""},
	"csgmesh":                       {"CSGMesh3D", ""},
	"csgpolygon":                    {"CSGPolygon3D", ""},
	"csgtorus":                      {"CSGTorus3D", ""},
	"csgcombiner":                   {"CSGCombiner3D", ""},
	"navigationpolygoninstance":     {"NavigationRegion2D", ""},
	"navigationmeshinstance":        {"NavigationRegion3D", ""},
	"navigation2d":                  {"", "removed; use NavigationRegion2D/NavigationAgent2D and NavigationServer2D"},
	"navigation":                    {"", "removed; use NavigationRegion3D/NavigationAgent3D and NavigationServer3D"},
	"ysort":                         {"", "removed; enable y_sort_enabled on a Node2D (CanvasItem.y_sort_enabled)"},
	"viewportcontainer":             {"SubViewportContainer", ""},
	"textureprogress":               {"TextureProgressBar", ""},
	"toolbutton":                    {"Button", "use a Button with flat = true"},
	"windowdialog":                  {"Window", ""},
	"popupdialog":                   {"Popup", ""},
	"videoplayer":                   {"VideoStreamPlayer", ""},
	"bakedlightmap":                 {"LightmapGI", ""},
	"giprobe":                       {"VoxelGI", ""},
	"reference":                     {"RefCounted", ""},
	"file":                          {"FileAccess", "use static FileAccess.open(path, FileAccess.READ)"},
	"directory":                     {"DirAccess", "use static DirAccess.open(path)"},
	"quat":                          {"Quaternion", ""},
	"transform":                     {"Transform3D", ""},
	"poolstringarray":               {"PackedStringArray", ""},
	"poolintarray":                  {"PackedInt32Array", ""},
	"poolrealarray":                 {"PackedFloat32Array", ""},
	"poolbytearray":                 {"PackedByteArray", ""},
	"poolvector2array":              {"PackedVector2Array", ""},
	"poolvector3array":              {"PackedVector3Array", ""},
	"poolcolorarray":                {"PackedColorArray", ""},
	"visualserver":                  {"RenderingServer", ""},
	"physics2dserver":               {"PhysicsServer2D", ""},
	"physicsserver":                 {"PhysicsServer3D", ""},
	"physics2ddirectspacestate":     {"PhysicsDirectSpaceState2D", ""},
	"physicsdirectspacestate":       {"PhysicsDirectSpaceState3D", ""},
	"physics2dshapequeryparameters": {"PhysicsShapeQueryParameters2D", ""},
	"arvrserver":                    {"XRServer", ""},
	"arvrcamera":                    {"XRCamera3D", ""},
	"arvrorigin":                    {"XROrigin3D", ""},
	"arvrcontroller":                {"XRController3D", ""},
	"spatialmaterial":               {"StandardMaterial3D", ""},
	"cubemesh":                      {"BoxMesh", ""},
	"shape":                         {"Shape3D", ""},
	"boxshape":                      {"BoxShape3D", ""},
	"sphereshape":                   {"SphereShape3D", ""},
	"capsuleshape":                  {"CapsuleShape3D", ""},
	"cylindershape":                 {"CylinderShape3D", ""},
	"convexpolygonshape":            {"ConvexPolygonShape3D", ""},
	"concavepolygonshape":           {"ConcavePolygonShape3D", ""},
	"heightmapshape":                {"HeightMapShape3D", ""},
	"planeshape":                    {"WorldBoundaryShape3D", ""},
	"lineshape2d":                   {"WorldBoundaryShape2D", ""},
	"rayshape":                      {"SeparationRayShape3D", ""},
	"rayshape2d":                    {"SeparationRayShape2D", ""},
	"world":                         {"World3D", ""},
	"streamtexture":                 {"CompressedTexture2D", ""},
	"audiostreamsample":             {"AudioStreamWAV", ""},
	"audiostreamoggvorbis":          {"AudioStreamOggVorbis", ""},
	"dynamicfont":                   {"FontFile", "or SystemFont"},
	"dynamicfontdata":               {"FontFile", ""},
	"bitmapfont":                    {"FontFile", ""},
	"animationtreeplayer":           {"AnimationTree", ""},
	"networkedmultiplayerenet":      {"ENetMultiplayerPeer", ""},
	"networkedmultiplayerpeer":      {"MultiplayerPeer", ""},
	"streampeerssl":                 {"StreamPeerTLS", ""},
	"gdnative":                      {"GDExtension", ""},
	"funcref":                       {"Callable", "use Callable(object, \"method\") or a method reference like my_func"},
	"joint":                         {"Joint3D", ""},
	"hingejoint":                    {"HingeJoint3D", ""},
	"pinjoint":                      {"PinJoint3D", ""},
	"sliderjoint":                   {"SliderJoint3D", ""},
	"conetwistjoint":                {"ConeTwistJoint3D", ""},
	"generic6dofjoint":              {"Generic6DOFJoint3D", ""},
	"editorspatialgizmo":            {"EditorNode3DGizmo", ""},
	"editorspatialgizmoplugin":      {"EditorNode3DGizmoPlugin", ""},
}

// memberRenames: старое имя метода/свойства/функции -> как это делается в Godot 4.
var memberRenames = map[string]string{
	"yield":                    "`yield` is gone: use `await signal` or `await some_coroutine()`",
	"instance":                 "PackedScene.instance() is now `instantiate()`",
	"rand_range":               "use `randf_range(from, to)` or `randi_range(from, to)`",
	"stepify":                  "use `snapped(value, step)`",
	"linear_interpolate":       "use `lerp()`: `a.lerp(b, t)` for vectors, `lerp(a, b, t)` for numbers",
	"deg2rad":                  "use `deg_to_rad()`",
	"rad2deg":                  "use `rad_to_deg()`",
	"str2var":                  "use `str_to_var()`",
	"var2str":                  "use `var_to_str()`",
	"to_json":                  "use `JSON.stringify(value)`",
	"parse_json":               "use `JSON.parse_string(text)`",
	"funcref":                  "use a Callable: `Callable(obj, \"method\")` or just `obj.method`",
	"update":                   "CanvasItem.update() is now `queue_redraw()`",
	"set_as_toplevel":          "use the `top_level` property",
	"change_scene":             "SceneTree.change_scene() is now `change_scene_to_file(path)`",
	"change_scene_to":          "SceneTree.change_scene_to() is now `change_scene_to_packed(packed_scene)`",
	"get_ticks_msec":           "OS.get_ticks_msec() moved to `Time.get_ticks_msec()`",
	"get_unix_time":            "OS.get_unix_time() moved to `Time.get_unix_time_from_system()`",
	"is_network_master":        "use `is_multiplayer_authority()`",
	"get_network_master":       "use `get_multiplayer_authority()`",
	"set_network_master":       "use `set_multiplayer_authority(id)`",
	"rect_position":            "Control.rect_position is now `position`",
	"rect_size":                "Control.rect_size is now `size`",
	"rect_min_size":            "Control.rect_min_size is now `custom_minimum_size`",
	"rect_global_position":     "Control.rect_global_position is now `global_position`",
	"rect_rotation":            "Control.rect_rotation is now `rotation` (radians) / `rotation_degrees`",
	"rect_scale":               "Control.rect_scale is now `scale`",
	"margin_left":              "Control margins are now `offset_left`/`offset_top`/`offset_right`/`offset_bottom`",
	"margin_top":               "Control margins are now `offset_left`/`offset_top`/`offset_right`/`offset_bottom`",
	"margin_right":             "Control margins are now `offset_left`/`offset_top`/`offset_right`/`offset_bottom`",
	"margin_bottom":            "Control margins are now `offset_left`/`offset_top`/`offset_right`/`offset_bottom`",
	"editor_hint":              "Engine.editor_hint is now `Engine.is_editor_hint()`",
	"empty":                    "Array/String/Dictionary.empty() is now `is_empty()`",
	"invert":                   "Array.invert() is now `reverse()`",
	"find_last":                "String/Array.find_last() is now `rfind()`",
	"get_rotation_degrees":     "rotation is in radians; use the `rotation_degrees` property",
	"set_rotation_degrees":     "rotation is in radians; use the `rotation_degrees` property",
	"export":                   "`export var x` is now the annotation `@export var x`",
	"onready":                  "`onready var x` is now `@onready var x`",
	"tool":                     "`tool` is now the annotation `@tool` at the top of the script",
	"setget":                   "setget is gone: declare `var x: int: set = _set_x, get = _get_x` or inline `set(value):` blocks",
	"remotesync":               "RPC keywords are now `@rpc(\"any_peer\", \"call_local\")` annotations",
	"puppet":                   "RPC keywords are now `@rpc` annotations",
	"master":                   "RPC keywords are now `@rpc` annotations",
	"get_world":                "Node3D.get_world() is now `get_world_3d()`",
	"move_and_slide_with_snap": "removed: set `velocity`, `floor_snap_length` and `up_direction` properties, then call `move_and_slide()` with no arguments",
	"move_and_slide":           "In Godot 4 CharacterBody2D/3D.move_and_slide() takes no arguments: set the `velocity` property first; it returns bool",
	"get_slide_count":          "use `get_slide_collision_count()`",
	"connect":                  "signals: `button.pressed.connect(_on_pressed)`; the string form `connect(\"pressed\", self, \"_on_pressed\")` is gone",
	"get_cell":                 "TileMap cell API changed (layers, atlas coords); in Godot 4.3+ use TileMapLayer.get_cell_source_id()/get_cell_atlas_coords()",
	"set_cell":                 "TileMap cell API changed; in Godot 4.3+ use TileMapLayer.set_cell(coords, source_id, atlas_coords)",
	"get_cellv":                "TileMap cell API changed; in Godot 4.3+ use TileMapLayer.get_cell_source_id(coords)",
	"set_cellv":                "TileMap cell API changed; in Godot 4.3+ use TileMapLayer.set_cell(coords, source_id, atlas_coords)",
	"world_to_map":             "use `local_to_map()`",
	"map_to_world":             "use `map_to_local()`",
}
