package project

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode/utf8"
)

// Лимиты, чтобы агент не утопил свой контекст одним вызовом.
const (
	MaxReadBytes   = 512 * 1024
	DefaultMaxList = 500
)

// FileEntry — элемент листинга.
type FileEntry struct {
	Path  string `json:"path"`
	IsDir bool   `json:"is_dir,omitempty"`
	Size  int64  `json:"size,omitempty"`
}

// ListOptions управляет листингом каталога.
type ListOptions struct {
	Recursive   bool
	Pattern     string // glob по имени файла, например "*.gd"
	IncludeMeta bool   // показывать *.import и *.uid
	Max         int
}

// List возвращает содержимое каталога проекта.
func (s *Sandbox) List(dir string, opt ListOptions) (entries []FileEntry, truncated bool, err error) {
	root, err := s.Resolve(dir)
	if err != nil {
		return nil, false, err
	}
	if opt.Max <= 0 {
		opt.Max = DefaultMaxList
	}
	errStop := errors.New("stop")

	walkErr := filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if p == root {
			return nil
		}
		name := d.Name()
		if d.IsDir() && (name == ".godot" || name == ".git" || name == ".import") {
			return fs.SkipDir
		}
		if !opt.IncludeMeta && !d.IsDir() && isMetaFile(name) {
			return nil
		}
		match := true
		if opt.Pattern != "" {
			match, _ = filepath.Match(opt.Pattern, name)
		}
		if match && (opt.Pattern == "" || !d.IsDir()) {
			if len(entries) >= opt.Max {
				truncated = true
				return errStop
			}
			e := FileEntry{Path: s.ToRes(p), IsDir: d.IsDir()}
			if info, err := d.Info(); err == nil && !d.IsDir() {
				e.Size = info.Size()
			}
			entries = append(entries, e)
		}
		if d.IsDir() && !opt.Recursive {
			return fs.SkipDir
		}
		return nil
	})
	if walkErr != nil && !errors.Is(walkErr, errStop) {
		return nil, false, walkErr
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Path < entries[j].Path })
	return entries, truncated, nil
}

func isMetaFile(name string) bool {
	return strings.HasSuffix(name, ".import") || strings.HasSuffix(name, ".uid")
}

// ReadResult — результат чтения текстового файла.
type ReadResult struct {
	Path       string `json:"path"`
	Content    string `json:"content"`
	StartLine  int    `json:"start_line"`
	EndLine    int    `json:"end_line"`
	TotalLines int    `json:"total_lines"`
	Truncated  bool   `json:"truncated,omitempty"`
}

// Read читает текстовый файл целиком или диапазон строк (нумерация с 1).
func (s *Sandbox) Read(path string, startLine, maxLines int) (*ReadResult, error) {
	abs, err := s.Resolve(path)
	if err != nil {
		return nil, err
	}
	info, err := os.Stat(abs)
	if err != nil {
		return nil, err
	}
	if info.IsDir() {
		return nil, fmt.Errorf("%s is a directory; use the list tool", path)
	}
	if info.Size() > 8*MaxReadBytes {
		return nil, fmt.Errorf("%s is too large (%d bytes)", path, info.Size())
	}
	data, err := os.ReadFile(abs)
	if err != nil {
		return nil, err
	}
	if !utf8.Valid(data) || bytes.IndexByte(data, 0) >= 0 {
		return nil, fmt.Errorf("%s looks like a binary file (e.g. .scn/.res/.png); only text files can be read", path)
	}

	lines := strings.SplitAfter(string(data), "\n")
	if len(lines) > 0 && lines[len(lines)-1] == "" {
		lines = lines[:len(lines)-1]
	}
	total := len(lines)
	if startLine < 1 {
		startLine = 1
	}
	if startLine > total && total > 0 {
		return nil, fmt.Errorf("start_line %d is past the end of the file (%d lines)", startLine, total)
	}
	end := total
	if maxLines > 0 && startLine-1+maxLines < total {
		end = startLine - 1 + maxLines
	}

	res := &ReadResult{Path: s.ToRes(abs), StartLine: startLine, TotalLines: total}
	var b strings.Builder
	for i := startLine - 1; i < end; i++ {
		if b.Len()+len(lines[i]) > MaxReadBytes {
			res.Truncated = true
			break
		}
		b.WriteString(lines[i])
		res.EndLine = i + 1
	}
	if res.EndLine < total {
		res.Truncated = true
	}
	res.Content = b.String()
	return res, nil
}

// Write атомарно записывает файл (через временный файл + rename).
func (s *Sandbox) Write(path, content string, createDirs bool) (created bool, err error) {
	abs, err := s.Resolve(path)
	if err != nil {
		return false, err
	}
	if strings.HasSuffix(abs, ".import") {
		return false, errors.New(".import files are generated by Godot; change import settings in the editor instead")
	}
	_, statErr := os.Stat(abs)
	created = errors.Is(statErr, fs.ErrNotExist)

	dir := filepath.Dir(abs)
	if createDirs {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return false, err
		}
	}
	tmp, err := os.CreateTemp(dir, ".mcp-write-*")
	if err != nil {
		return false, err
	}
	defer os.Remove(tmp.Name()) // no-op после успешного rename
	if _, err := tmp.WriteString(content); err != nil {
		tmp.Close()
		return false, err
	}
	if err := tmp.Close(); err != nil {
		return false, err
	}
	mode := os.FileMode(0o644)
	if info, err := os.Stat(abs); err == nil {
		mode = info.Mode().Perm()
	}
	if err := os.Chmod(tmp.Name(), mode); err != nil {
		return false, err
	}
	return created, os.Rename(tmp.Name(), abs)
}

// Edit заменяет oldStr на newStr. Без replaceAll oldStr должна встречаться
// ровно один раз — так агент не испортит файл неоднозначной правкой.
func (s *Sandbox) Edit(path, oldStr, newStr string, replaceAll bool) (replacements int, err error) {
	if oldStr == "" {
		return 0, errors.New("old_str must not be empty")
	}
	res, err := s.Read(path, 1, 0)
	if err != nil {
		return 0, err
	}
	if res.Truncated {
		return 0, errors.New("file is too large to edit safely")
	}
	n := strings.Count(res.Content, oldStr)
	switch {
	case n == 0:
		return 0, errors.New("old_str not found; re-read the file and copy the text exactly (tabs vs spaces matter in GDScript)")
	case n > 1 && !replaceAll:
		return 0, fmt.Errorf("old_str occurs %d times; add surrounding context to make it unique or set replace_all", n)
	}
	limit := 1
	if replaceAll {
		limit = -1
	}
	updated := strings.Replace(res.Content, oldStr, newStr, limit)
	if _, err := s.Write(path, updated, false); err != nil {
		return 0, err
	}
	return n, nil
}
